# Pick all files of a given SRCFILES and include them in one .cpp file BIGFILE
macro(AllFilesInOne BIGFILE SRCFILES)
	# Inspired by http://cmake.org/Wiki/CMakeMacroCreateFinalFile
	FILE(REMOVE ${BIGFILE})
	FILE(WRITE ${BIGFILE} "// Autogenerated by CMake\n\n")
	FOREACH (CURRENT_FILE ${SRCFILES})
		get_filename_component(INCLUDE_NAME ${CURRENT_FILE} NAME)
		FILE(APPEND ${BIGFILE} "#include \"${INCLUDE_NAME}\"\n")	
	ENDFOREACH (CURRENT_FILE)
	message(STATUS "++ ${BIGFILE} generated")
endmacro(AllFilesInOne)
